# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres
    container_name: sonja_db
    restart: always
    ports:
      - "5432:5432"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_PASSWORD: example
